In [1]:
# Exercise 1: Concatenate
# Concept: Concatenation is like stacking papers on top of each other. 
#     You can stack rows (axis=0) or columns (axis=1).

In [2]:
import pandas as pd
import numpy as np

In [7]:
df1 = pd.DataFrame([['a', 1], ['b', 2]], columns=['letter', 'number'])
df2 = pd.DataFrame([['c', 1], ['d', 2]], columns=['letter', 'number'])

print("DataFrame 1:")
print(df1)
print("\nDataFrame 2:")
print(df2)

# Concatenate and reset index
result = pd.concat([df1, df2], axis=0, ignore_index=True)
print("\nConcatenated DataFrame:")
print(result)
print(f"Index type: {type(result.index)}")

DataFrame 1:
  letter  number
0      a       1
1      b       2

DataFrame 2:
  letter  number
0      c       1
1      d       2

Concatenated DataFrame:
  letter  number
0      a       1
1      b       2
2      c       1
3      d       2
Index type: <class 'pandas.core.indexes.range.RangeIndex'>

  letter  number
0      a       1
1      b       2
2      c       1
3      d       2

In [9]:
# Exercise 2: Merge - Joining DataFrames
## Concept: Merging is like joining two tables in a database. 
## You specify which column(s) to match on.

In [10]:
#df1

df1_dict = {
        'id': ['1', '2', '3', '4', '5'],
        'Feature1': ['A', 'C', 'E', 'G', 'I'],
        'Feature2': ['B', 'D', 'F', 'H', 'J']}

df1 = pd.DataFrame(df1_dict, columns = ['id', 'Feature1', 'Feature2'])

#df2
df2_dict = {
        'id': ['1', '2', '6', '7', '8'],
        'Feature1': ['K', 'M', 'O', 'Q', 'S'],
        'Feature2': ['L', 'N', 'P', 'R', 'T']}

df2 = pd.DataFrame(df2_dict, columns = ['id', 'Feature1', 'Feature2'])

In [11]:
### Inner join
pd.merge(df1, df2, on='id', how='inner')

  id Feature1_x Feature2_x Feature1_y Feature2_y
0  1          A          B          K          L
1  2          C          D          M          N

In [17]:
### Outer Join: All ids from both tables
pd.merge(df1, df2, on='id', how='outer', suffixes=("_df1", "_df2"))

  id Feature1_df1 Feature2_df1 Feature1_df2 Feature2_df2
0  1            A            B            K            L
1  2            C            D            M            N
2  3            E            F          NaN          NaN
3  4            G            H          NaN          NaN
4  5            I            J          NaN          NaN
5  6          NaN          NaN            O            P
6  7          NaN          NaN            Q            R
7  8          NaN          NaN            S            T

In [15]:
# Types of Merges:

# inner: Only rows that match in both DataFrames
# outer: All rows from both DataFrames (fills missing with NaN)
# left: All rows from left DataFrame
# right: All rows from right DataFrame

In [16]:
# Exercise 3: Merge with MultiIndex
## Concept: MultiIndex is like having multiple layers of organization - think of a filing cabinet with drawers (level 1) and folders within drawers (level 2).

In [18]:
#generate days
all_dates = pd.date_range('2021-01-01', '2021-12-15')
business_dates = pd.bdate_range('2021-01-01', '2021-12-31')

#generate tickers
tickers = ['AAPL', 'FB', 'GE', 'AMZN', 'DAI']

#create indexs
index_alt = pd.MultiIndex.from_product([all_dates, tickers], names=['Date', 'Ticker'])
index = pd.MultiIndex.from_product([business_dates, tickers], names=['Date', 'Ticker'])

# create DFs
market_data = pd.DataFrame(index=index,
                        data=np.random.randn(len(index), 3),
                        columns=['Open','Close','Close_Adjusted'])

alternative_data = pd.DataFrame(index=index_alt,
                                data=np.random.randn(len(index_alt), 2),
                                columns=['Twitter','Reddit'])

In [23]:
market_data, alternative_data

(                       Open     Close  Close_Adjusted
 Date       Ticker
 2021-01-01 AAPL    0.174457 -0.812895       -0.768977
            FB     -0.946040  0.951444        0.762498
            GE      1.032878  0.251804       -0.777880
            AMZN   -0.687413 -0.740222        0.903671
            DAI    -0.148273 -0.619935        0.204568
 ...                     ...       ...             ...
 2021-12-31 AAPL   -0.242549 -0.755502       -0.367903
            FB      1.055587 -1.189466        1.098909
            GE      0.594349 -0.552820        0.131157
            AMZN   -0.679195 -0.705586       -1.682160
            DAI     0.491393 -0.138243       -0.963209

 [1305 rows x 3 columns],
                     Twitter    Reddit
 Date       Ticker
 2021-01-01 AAPL    0.412369  0.814799
            FB      1.800357  0.746210
            GE     -0.074411  1.041564
            AMZN   -0.425784 -0.513975
            DAI    -1.174780  0.433506
 ...                     ...       ...
 2021-12-15 AAPL   -2.206613 -0.682707
            FB      0.090327  0.536590
            GE      0.170704 -2.026294
            AMZN   -1.190580 -1.257097
            DAI     0.273327  0.509925

 [1745 rows x 2 columns])

In [25]:
market_data.merge(alternative_data, how='left', left_index=True, right_index=True).fillna(0)

                       Open     Close  Close_Adjusted   Twitter    Reddit
Date       Ticker
2021-01-01 AAPL    0.174457 -0.812895       -0.768977  0.412369  0.814799
           FB     -0.946040  0.951444        0.762498  1.800357  0.746210
           GE      1.032878  0.251804       -0.777880 -0.074411  1.041564
           AMZN   -0.687413 -0.740222        0.903671 -0.425784 -0.513975
           DAI    -0.148273 -0.619935        0.204568 -1.174780  0.433506
...                     ...       ...             ...       ...       ...
2021-12-31 AAPL   -0.242549 -0.755502       -0.367903  0.000000  0.000000
           FB      1.055587 -1.189466        1.098909  0.000000  0.000000
           GE      0.594349 -0.552820        0.131157  0.000000  0.000000
           AMZN   -0.679195 -0.705586       -1.682160  0.000000  0.000000
           DAI     0.491393 -0.138243       -0.963209  0.000000  0.000000

[1305 rows x 5 columns]

In [26]:
# Alternatively
market_data.join(alternative_data, how="left").fillna(0)

                       Open     Close  Close_Adjusted   Twitter    Reddit
Date       Ticker
2021-01-01 AAPL    0.174457 -0.812895       -0.768977  0.412369  0.814799
           FB     -0.946040  0.951444        0.762498  1.800357  0.746210
           GE      1.032878  0.251804       -0.777880 -0.074411  1.041564
           AMZN   -0.687413 -0.740222        0.903671 -0.425784 -0.513975
           DAI    -0.148273 -0.619935        0.204568 -1.174780  0.433506
...                     ...       ...             ...       ...       ...
2021-12-31 AAPL   -0.242549 -0.755502       -0.367903  0.000000  0.000000
           FB      1.055587 -1.189466        1.098909  0.000000  0.000000
           GE      0.594349 -0.552820        0.131157  0.000000  0.000000
           AMZN   -0.679195 -0.705586       -1.682160  0.000000  0.000000
           DAI     0.491393 -0.138243       -0.963209  0.000000  0.000000

[1305 rows x 5 columns]